FROM catthehacker/ubuntu:act-latest

ARG PHP_VERSION=8.5.6

RUN set -ex && apt-get update \
    && apt-get install -y ca-certificates curl gnupg iputils-ping libicu-dev sudo --no-install-recommends

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpng-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 4. Install native PHP extensions
RUN docker-php-ext-install pdo_mysql gd
