<div>
    <x-filament::icon-button
        icon="phosphor-arrows-clockwise-light"
        :tooltip="__('filament.maintenance_clear_cache')"
        color="gray"
        wire:click="clear"
        class="fi-clear-caches-btn"
    />
</div>
