<?php

namespace App\Support\Dto\SimBriefOfp;

use Spatie\LaravelData\Dto;

final class SimBriefOfpApiParams extends Dto
{
    public function __construct(
        public string $airline,
        public string $fltnum,
        public string $type,
        public string $orig,
        public string $dest,
        public int $date,
        public int $dephour,
        public int $depmin,
        public string $route,
        public int $stehour,
        public int $stemin,
        public string $reg,
        public string $fin,
        public string $selcal,
        public string $pax,
        public string $altn,
        public string $fl,
        public string $cpt,
        public int $pid,
        public string $fuelfactor,
        public string $manualpayload,
        public string $manualzfw,
        public int $taxifuel,
        public int $minfob,
        public string $minfob_units,
        public int $minfod,
        public string $minfod_units,
        public int $melfuel,
        public string $melfuel_units,
        public int $atcfuel,
        public string $atcfuel_units,
        public int $wxxfuel,
        public string $wxxfuel_units,
        public int $addedfuel,
        public string $addedfuel_units,
        public string $addedfuel_label,
        public int $tankering,
        public string $tankering_units,
        public string $flightrules,
        public string $flighttype,
        public string $contpct,
        public string $resvrule,
        public int $taxiout,
        public int $taxiin,
        public string $cargo,
        public string $origrwy,
        public string $destrwy,
        public string $climb,
        public string $descent,
        public string $cruisemode,
        public string $cruisesub,
        public string $planformat,
        public bool $pounds,
        public bool $navlog,
        public bool $etops,
        public bool $stepclimbs,
        public bool $tlr,
        public bool $notams_opt,
        public bool $firnot,
        public bool $maps,
        public string $turntoflt,
        public string $turntoapt,
        public string $turntotime,
        public string $turnfrflt,
        public string $turnfrapt,
        public string $turnfrtime,
        public string $fuelstats,
        public string $contlabel,
        public string $static_id,
        public string $acdata,
        public string $acdata_parsed
    ) {}
}
